# Generated by Django 5.2.6 on 2025-10-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooldefinition',
            name='category',
            field=models.CharField(db_index=True, help_text='Category name (must match a ToolCategory.name)', max_length=50),
        ),
    ]
