# Generated by Django 5.2.6 on 2025-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_tools', '0002_alter_tooldefinition_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tool Categories'},
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='description',
            field=models.TextField(blank=True, help_text='What types of tools belong in this category'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='display_name',
            field=models.CharField(help_text="Human-readable name (e.g., 'Wellbeing & Check-ins')", max_length=100),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='name',
            field=models.CharField(db_index=True, help_text="Category identifier (lowercase, no spaces, e.g., 'wellbeing')", max_length=50, unique=True),
        ),
    ]
