# Generated by Django 6.0 on 2025-12-23 15:49

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(default='gemma3-32k:latest', max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('max_context_tokens', models.IntegerField(default=32768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('summary_needs_regeneration', models.BooleanField(default=False, help_text='Flag indicating new messages since last summary')),
                ('summary_message_count', models.IntegerField(default=0, help_text='Number of messages included in current summary')),
                ('short_term_memory', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Embedding of the conversation summary', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(help_text="The user's input message")),
                ('ai_response', models.TextField(help_text="The AI's final text response")),
                ('ai_reasoning', models.TextField(blank=True, help_text='Internal thought process (ThinkingPart)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
