# Generated by Django 6.0 on 2025-12-25 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, help_text="Custom name for this agent (e.g., 'Steve', 'Kevin')", max_length=100)),
                ('communication_style', models.CharField(blank=True, help_text="Communication style preference (e.g., 'supportive', 'drill sergeant', 'casual')", max_length=100)),
                ('response_length', models.CharField(blank=True, help_text="Preferred response length (e.g., 'concise', 'detailed', 'moderate')", max_length=50)),
                ('formality_level', models.CharField(blank=True, help_text="Formality preference (e.g., 'casual', 'professional', 'formal')", max_length=50)),
                ('language', models.CharField(blank=True, default='en', help_text="Preferred language code (e.g., 'en', 'es', 'fr')", max_length=10)),
                ('additional_preferences', models.JSONField(blank=True, default=dict, help_text='Additional customization preferences as key-value pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'agent')},
            },
        ),
    ]
