# Generated by Django 6.0 on 2026-01-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_useragentpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='debug_data',
            field=models.JSONField(blank=True, help_text='Complete pydantic-ai result with all messages, tool calls, thinking, and usage stats', null=True),
        ),
    ]
