# Generated by Django 5.2.6 on 2025-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiidentityprofile',
            name='preferred_model',
            field=models.CharField(default='llama3.2:latest', help_text='Ollama model to use (e.g., llama3.2:latest, mistral:latest)', max_length=100),
        ),
    ]
