# Generated by Django 5.2.6 on 2025-09-29 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcontextprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmcontextprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
