# Generated by Django 5.2.6 on 2025-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_aiidentityprofile_preferred_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='checkin_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Check-in schedule configuration with weekday/weekend times'),
        ),
    ]
