# Generated by Django 5.2.6 on 2025-10-01 09:59

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_llmcontextprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmcontextprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='llmcontextprofile',
            name='date_of_birth',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, help_text="User's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='llmcontextprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
