# Generated by Django 5.2.6 on 2025-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_checkin_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='checkin_notifications',
            field=models.BooleanField(default=True, help_text='Enable/disable check-in notifications'),
        ),
    ]
