# Generated by Django 5.2.6 on 2025-10-01 18:00

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_llmcontextprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcontextprofile',
            name='location',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="User's location (city, country)", null=True),
        ),
    ]
