# Generated by Django 5.2.6 on 2025-10-02 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_llmcontextprofile_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIdentityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_model', models.CharField(default='gemma3:latest', help_text='Ollama model to use (e.g., gemma3:latest, llama3.2:latest)', max_length=100)),
                ('ai_name', models.CharField(default='LifePal', help_text='What the AI calls itself', max_length=100)),
                ('ai_role', models.CharField(default='supportive life assistant and wellbeing companion', help_text="The AI's primary role/purpose", max_length=200)),
                ('ai_personality_traits', models.TextField(default='empathetic, non-judgmental, supportive, encouraging, warm', help_text='Comma-separated personality traits')),
                ('core_instructions', models.TextField(default='You are a supportive AI companion focused on mental wellbeing and personal growth. Listen actively, ask thoughtful questions, and provide encouragement. Never judge, always validate feelings, and help users reflect on their experiences.', help_text='Core behavioral instructions for the AI')),
                ('communication_style', models.TextField(default='conversational, warm, and empathetic', help_text='How the AI should communicate')),
                ('response_length_preference', models.CharField(choices=[('concise', 'Concise (1-2 sentences)'), ('moderate', 'Moderate (2-4 sentences)'), ('detailed', 'Detailed (4+ sentences)')], default='moderate', help_text='Preferred response length', max_length=20)),
                ('topics_to_emphasize', models.TextField(blank=True, help_text="Topics the AI should focus on (e.g., 'gratitude, mindfulness, relationships')")),
                ('topics_to_avoid', models.TextField(blank=True, help_text='Topics the AI should avoid or handle carefully')),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional custom instructions or preferences')),
                ('use_emojis', models.BooleanField(default=True, help_text='Whether AI should use emojis in responses')),
                ('formality_level', models.CharField(choices=[('casual', 'Casual (friendly, informal)'), ('balanced', 'Balanced (professional yet warm)'), ('formal', 'Formal (professional, structured)')], default='balanced', max_length=20)),
                ('question_frequency', models.CharField(choices=[('low', 'Low (mostly listen)'), ('moderate', 'Moderate (balanced)'), ('high', 'High (ask many questions)')], default='moderate', help_text='How often the AI asks follow-up questions', max_length=20)),
                ('remember_preferences', models.BooleanField(default=True, help_text='Whether to reference past conversations and preferences')),
                ('proactive_suggestions', models.BooleanField(default=True, help_text='Whether AI can make proactive suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Identity Profile',
                'verbose_name_plural': 'AI Identity Profiles',
            },
        ),
    ]
