# Generated by Django 6.0 on 2025-12-27 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Exercise name (e.g., 'stationary bike run')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about the exercise')),
                ('instructions', models.JSONField(default=list, help_text='Step-by-step instructions as array of strings')),
                ('tracks_reps', models.BooleanField(default=False, help_text='Can track repetitions (e.g., push-ups, squats)')),
                ('tracks_weight', models.BooleanField(default=False, help_text='Can track weight/resistance (e.g., barbell exercises)')),
                ('tracks_duration', models.BooleanField(default=False, help_text='Can track duration (e.g., planks, cardio)')),
                ('tracks_distance', models.BooleanField(default=False, help_text='Can track distance (e.g., running, cycling)')),
                ('tracks_pace', models.BooleanField(default=False, help_text='Can track pace/speed (e.g., running, cycling)')),
                ('is_custom', models.BooleanField(default=False, help_text='True if created by user, False if from dataset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_areas', models.ManyToManyField(blank=True, help_text='Body areas/regions targeted', related_name='exercises', to='fitness.bodyarea')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this custom exercise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
                ('equipment_required', models.ManyToManyField(blank=True, help_text='Equipment needed for this exercise', related_name='exercises', to='fitness.equipment')),
                ('secondary_body_parts', models.ManyToManyField(blank=True, help_text='Secondary body part engaged', related_name='exercises_as_secondary', to='fitness.bodypart')),
                ('target_body_parts', models.ManyToManyField(blank=True, help_text='Primary body part targeted', related_name='exercises_as_primary', to='fitness.bodypart')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='fitness_exe_name_91210a_idx')],
            },
        ),
    ]
