# Generated by Django 6.0 on 2025-12-27 20:58

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Semantic embedding for the exercise (pgvector)', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the embedding was generated', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='embedding_model',
            field=models.CharField(blank=True, default='', help_text='Name of the model used to generate the embedding', max_length=128),
        ),
    ]
