# Generated by Django 6.0 on 2026-01-01 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_exercise_embedding_exercise_embedding_generated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('success_metrics', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Test name or type (e.g., 'Strength Assessment Jan 2026')", max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessTestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this test exercise in the test')),
                ('instructions', models.TextField(blank=True, help_text='Custom instructions for this test exercise', null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds (if applicable)', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distance in meters (if applicable)', null=True)),
                ('pace', models.FloatField(blank=True, help_text='Pace (e.g., min/km, if applicable)', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('attempted', 'Attempted'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (kg, reps, sec, m, etc)', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('fitness_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_exercises', to='fitness.fitnesstest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserFitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_level', models.CharField(choices=[('inactive', 'Inactive'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=20)),
                ('exercises_per_week', models.PositiveIntegerField(default=0)),
                ('runs_per_week', models.PositiveIntegerField(default=0)),
                ('exercise_days', models.JSONField(default=list)),
                ('run_days', models.JSONField(default=list)),
                ('exercise_location', models.CharField(choices=[('home', 'Home'), ('gym', 'Gym'), ('both', 'Both')], max_length=20)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('restrictions', models.TextField(blank=True, null=True)),
                ('available_equipment', models.ManyToManyField(blank=True, to='fitness.equipment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('attempted', 'Attempted'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this set in the workout')),
                ('notes', models.TextField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Number of repetitions (if applicable)', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kilograms (if applicable)', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds (if applicable)', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distance in meters (if applicable)', null=True)),
                ('pace', models.FloatField(blank=True, help_text='Pace (e.g., min/km, if applicable)', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('attempted', 'Attempted'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='fitness.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('number_of_workouts', models.PositiveIntegerField()),
                ('number_of_runs', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='fitness.workoutplan'),
        ),
        migrations.CreateModel(
            name='ExcludedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='FavouriteExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
