# Generated by Django 6.0 on 2026-01-01 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_fitnessgoal_fitnesstest_fitnesstestexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitnessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfitnessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
