# Generated by Django 6.0 on 2026-01-01 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_userfitnessprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('body_fat', 'Body Fat Percentage (%)'), ('bmi', 'Body Mass Index (BMI)'), ('muscle_mass', 'Muscle Mass (kg)'), ('waist_circumference', 'Waist Circumference (cm)'), ('hip_circumference', 'Hip Circumference (cm)'), ('bicep_circumference', 'Bicep Circumference (cm)'), ('chest_circumference', 'Chest Circumference (cm)'), ('thigh_circumference', 'Thigh Circumference (cm)')], max_length=50)),
                ('value', models.FloatField()),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
