# Generated by Django 5.2.6 on 2025-10-01 18:00

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="E.g., 'Happy', 'Anxious', 'Calm'", max_length=50, unique=True)),
                ('emoji', models.CharField(blank=True, help_text='Emoji representation', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emotion',
                'verbose_name_plural': 'Emotions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The date this log represents')),
                ('summary', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='AI-generated summary of the day', null=True)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the day is complete and summarized')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('what_happened', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Description of what happened', null=True)),
                ('when_it_happened', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='When the moment occurred', null=True)),
                ('how_it_felt', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='How it made the user feel', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='moments/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='wellbeing.dailylog')),
            ],
            options={
                'verbose_name': 'Moment',
                'verbose_name_plural': 'Moments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_type', models.CharField(choices=[('morning', 'Morning Catch-up'), ('midday', 'Lunch Check-in'), ('evening', 'Evening Reflection')], max_length=20)),
                ('physical_feeling', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='How user feels physically')),
                ('mental_feeling', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='How user feels mentally')),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Additional notes from the check-in')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='llm_chat.conversation')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='wellbeing.dailylog')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['completed_at'],
                'unique_together': {('daily_log', 'check_in_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyLogEmotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intensity', models.IntegerField(default=5, help_text='Intensity from 1-10')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='wellbeing.dailylog')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellbeing.emotion')),
            ],
            options={
                'verbose_name': 'Daily Log Emotion',
                'verbose_name_plural': 'Daily Log Emotions',
                'unique_together': {('daily_log', 'emotion')},
            },
        ),
    ]
