# Generated by Django 5.2.6 on 2025-10-06 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0002_conversation_conversation_type_and_more'),
        ('wellbeing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Check-in', 'verbose_name_plural': 'Check-ins'},
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checkin',
            name='actions_taken',
            field=models.JSONField(blank=True, default=list, help_text="List of actions LLM performed (e.g., [{action: 'create_reminder', time: '17:30', type: 'midday'}])"),
        ),
        migrations.AddField(
            model_name='checkin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='insights',
            field=models.JSONField(blank=True, default=dict, help_text='Structured insights extracted by LLM (emotions, concerns, highlights, etc.)'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='When this check-in was scheduled for', null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When user opened the chat', null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief LLM-generated summary of the check-in'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='trigger_context',
            field=models.JSONField(blank=True, default=dict, help_text='Context that triggered this check-in (e.g., stressful event mentioned in morning)'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_in_type',
            field=models.CharField(choices=[('morning', 'Morning Catch-up'), ('midday', 'Midday Check-in'), ('evening', 'Evening Reflection'), ('adhoc', 'Ad-hoc Check-in')], max_length=20),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When conversation ended', null=True),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['daily_log', 'check_in_type'], name='wellbeing_c_daily_l_9ce04e_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['status'], name='wellbeing_c_status_95f568_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['scheduled_time'], name='wellbeing_c_schedul_08c956_idx'),
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='mental_feeling',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='physical_feeling',
        ),
    ]
