# Generated by Django 5.2.6 on 2025-10-06 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('general', 'General Chat'), ('checkin', 'Check-in')], default='general', help_text='Type of conversation - check-ins are excluded from general chat history', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'conversation_type'], name='llm_chat_co_user_id_795e61_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', '-updated_at'], name='llm_chat_co_convers_f5fcf7_idx'),
        ),
    ]
