# Generated by Django 5.2.6 on 2025-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0002_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('trigger', 'Trigger')], max_length=10),
        ),
    ]
