# Generated by Django 5.2.6 on 2025-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0003_alter_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="If True, this message won't be displayed in the UI"),
        ),
    ]
