# Generated by Django 5.2.6 on 2025-10-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0004_message_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_hidden',
        ),
    ]
